version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin@123
      PGDATA: /var/lib/postgresql/data/pgdata
    ports: 
        - 5432:5432
    volumes: 
        - /opt/postgres:/var/lib/postgresql/data
